<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Actions\" />
    <Folder Include="Execution\" />
    <Folder Include="Providers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DashboardStudio.Contracts\DashboardStudio.Contracts.csproj" />
    <ProjectReference Include="..\DashboardStudio.Core\DashboardStudio.Core.csproj" />
    <ProjectReference Include="..\DashboardStudio.Models\DashboardStudio.Models.csproj" />
  </ItemGroup>

</Project>
